name: galaxeus_lib_flutter
description: Library for make flutter more easy and more short with universal extension, utils, and more.
version: 0.0.8
homepage: https://github.com/azkadev
 
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  
# flutter:
 