name: galaxeus_lib_flutter
description: Library for make flutter more easy and more short with universal extension, utils, and more.
version: 0.0.0
homepage: https://github.com/azkadev

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
 